<?php
/**
 * @file
 * Common functionality used across aGov.
 *
 * @copyright Copyright(c) 2012 PreviousNext
 * @license GPL v2 http://www.fsf.org/licensing/licenses/gpl.html
 * @author Chris Skene chris at previousnext dot com dot au
 */

/**
 * Implements hook_menu().
 */
function agov_core_menu() {
  $items['about-agov'] = array(
    'title' => 'About aGov',
    'page callback' => 'agov_core_about_agov_page',
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Page callback for about aGov page.
 *
 * @return array
 *   A render array for the page callback.
 */
function agov_core_about_agov_page() {
  $output = array(
    'about' => array(
      '#type' => 'markup',
      '#markup' => "<p>" . l(t('aGov'), 'http://agov.com.au') . " is a free open source Drupal 7 distribution developed specifically for Australian government organisations.</p>",
    ),
    'previousnext' => array(
      '#type' => 'markup',
      '#markup' => "<p>aGov is designed and developed by " . l(t('PreviousNext'), 'http://previousnext.com.au') . " and is free to " . l(t("download"), "https://drupal.org/project/agov") . ".</p>",
    ),
  );
  return $output;
}

/**
 * Returns a list of the themes that aGov supports.
 */
function agov_core_theme_info() {
  return array(
    AGOV_DEFAULT_THEME,
  );
}

/**
 * Implements hook_form_alter().
 */
function agov_core_form_alter(&$form, &$form_alter, $form_id) {

  // Check if this is the node_freshness config form.
  if ($form_id == 'node_freshness_config') {
    $form['agov_help'] = array(
      '#markup' => '<p>' . t('Node freshness is a general value available across the site for governing when content is considered "stale" or archiveable.') . '</p>',
      '#weight' => '-50',
    );
    if (module_exists('agov_news')) {
      $form['agov_help']['#markup'] .= '<p>' . t('Currently, this value determines when News items are moved to the Archived section.') . '</p>';
    }
  }

  // Install Canberra timezone.
  if ($form_id == 'system_regional_settings') {
    $timezone_form = $form['timezone']['date_default_timezone'];
    $sydney_tz = $timezone_form['#options']['Australia/Sydney'];
    $sydney_re = '/Sydney/';
    $canberra_tz = preg_replace($sydney_re, 'Canberra', $sydney_tz, 1);
    $timezone_form['#options']['Australia/Canberra'] = $canberra_tz;
    asort($timezone_form['#options']);
    $form['timezone']['date_default_timezone'] = $timezone_form;
  }
}

/**
 * Implements hook_block_info().
 */
function agov_core_block_info() {
  $blocks = array();

  $blocks['update_notification'] = array(
    'info' => t('aGov Update Notification'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function agov_core_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'update_notification':
      $block['content'] = "<div class=\"messages warning\">This site is running on the aGov distribution. aGov ships with a number of patched and development status modules that have been tested to work together. Avoid updating modules included with aGov independently. See the <a href=\"http://drupal.org/project/agov\">aGov project page</a> on drupal.org for further information about releases.</div>";
      break;
  }

  return $block;
}

/**
 * Implements hook_entity_info_alter().
 */
function agov_core_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['blog_teaser'] = array(
    'label' => t('Blog Teaser'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_metatag_config_default_alter().
 */
function agov_core_metatag_config_default_alter(&$configs) {
  $configs['global']->config['DCTERMS.creator'] = array('value' => '[site:name]');
  $configs['global']->config['DCTERMS.date'] = array('value' => '[current-date:custom:Y-m-d\TH:iP]');
  $configs['global']->config['DCTERMS.description'] = array('value' => '[site:slogan]');
  $configs['global']->config['DCTERMS.language'] = array('value' => 'en');
  $configs['global']->config['DCTERMS.publisher'] = array('value' => '[site:name]');
  $configs['global']->config['DCTERMS.subject'] = array('value' => '[site:slogan]');
  $configs['global']->config['DCTERMS.type'] = array('value' => 'other');
  $configs['node']->config['DCTERMS.language'] = array('value' => 'en');
}

/**
 * Implements hook_block_info_alter().
 */
function agov_core_block_info_alter(&$blocks, $theme, $code_blocks) {
  $blocks['system']['help']['region'] = 'content';
  $blocks['superfish'][1]['title'] = '<none>';
  $blocks['system']['user-menu']['title'] = '<none>';
}
