<?php
/**
 * @file
 * Drupal needs this blank file.
 */

use Drupal\fabricator\Worker\Bean as BeanFabricator;

/**
 * Sets up news related beans.
 */
function agov_content_news_article_setup_beans() {

  $t = get_t();

  // Add menu links to main menu.
  $menus = array(
    'current-news' => 'news-media/news',
    'archived-news' => 'news-media/news-archive',
    'media-releases' => 'news-media/media-releases',
    'events' => 'news-media/events',
    'blog' => 'news-media/blog',
  );

  // @todo - Save these menu items below the news-media item.
  // Save the images required for these block.
  $files = array();
  $images = array(
    'news-media-intro' => 'news-media.jpg',
    'current-news' => 'news-archives.jpg',
    'archived-news' => 'news-archives.jpg',
    'media-releases' => 'media-releases.jpg',
    'events' => 'events.jpg',
    'blog' => 'news-media.jpg',
  );
  foreach ($images as $delta => $image) {
    // Load the files contents.
    $handle = fopen(dirname(__FILE__) . '/images/' . $image, 'r');
    // Returns the new file object.
    $files[$delta] = file_save_data($handle, 'public://' . $image, FILE_EXISTS_RENAME);
    fclose($handle);
  }

  // Install the required blocks.
  // Beans to be installed.
  $beans = array(
    // News and Media Intro block for the News & Media page.
    'news-media-intro' => array(
      'label' => $t('News and Media Intro'),
      'title' => '',
      'description' => $t('Provides a "News and Media Intro" bean that gives overview for the News & Media page.'),
      'type' => 'image_and_text',
      'view_mode' => 'hightlight',
      'fields' => array(
        // Image field.
        'field_bean_image' => array(
          '0' => array(
            'fid' => $files['news-media-intro']->fid,
            'alt' => t('News and Media Intro'),
            'title' => t('News and Media Intro'),
          ),
        ),
        // Text field.
        'field_bean_text' => array(
          '0' => array(
            'value' => 'Optional intro block with image Est porttitor hac ultricies nec integer enim scelerisque proin sagittis porttitor, sit! Magnis sit egestas turpis parturient aliquam. Mauris duis nascetur vel porttitor scelerisque cursus nec, in dis sit sagittis, lacus lacus?',
            'format' => 'rich_text',
          ),
        ),
      ),
    ),

    // Current News block.
    'current-news' => array(
      'label' => $t('Current News'),
      'title' => $t('Current News'),
      'description' => $t('Provides a "Current News" bean for the News & Media page.'),
      'type' => 'image_and_text',
      'view_mode' => 'default',
      'fields' => array(
        // Image field.
        'field_bean_image' => array(
          '0' => array(
            'fid' => $files['current-news']->fid,
            'alt' => t('Current News'),
            'title' => t('Current News'),
          ),
        ),
        // Text field.
        'field_bean_text' => array(
          '0' => array(
            'value' => 'Vel quis etiam enim pulvinar, tincidunt porttitor dignissim cum, dignissim sociis natoque, elementum nec scelerisque pulvinar, nascetur mauris mauris, a? Rhoncus augue et nunc, adipiscing tincidunt, sagittis, amet!',
            'format' => 'rich_text',
          ),
        ),
        // Link to field.
        'field_link_to' => array(
          '0' => array(
            'url' => $menus['current-news'],
            'title' => '',
            'attributes' => '',
          ),
        ),
      ),
    ),

    // Archived News block.
    'archived-news' => array(
      'label' => $t('Archived News'),
      'title' => $t('Archived News'),
      'description' => $t('Provides a "Archived News" bean for the News & Media page.'),
      'type' => 'image_and_text',
      'view_mode' => 'default',
      'fields' => array(
        // Image field.
        'field_bean_image' => array(
          '0' => array(
            'fid' => $files['archived-news']->fid,
            'alt' => t('Archived News'),
            'title' => t('Archived News'),
          ),
        ),
        // Text field.
        'field_bean_text' => array(
          '0' => array(
            'value' => 'Vel quis etiam enim pulvinar, tincidunt porttitor dignissim cum, dignissim sociis natoque, elementum nec scelerisque pulvinar, nascetur mauris mauris, a? Rhoncus augue et nunc, adipiscing tincidunt, sagittis, amet!',
            'format' => 'rich_text',
          ),
        ),
        // Link to field.
        'field_link_to' => array(
          '0' => array(
            'url' => $menus['archived-news'],
            'title' => '',
            'attributes' => '',
          ),
        ),
      ),
    ),

    // Media releases.
    'media-releases' => array(
      'label' => $t('Media Releases'),
      'title' => $t('Media Releases'),
      'description' => $t('Provides a "Media Releases" bean for the News & Media page.'),
      'type' => 'image_and_text',
      'view_mode' => 'default',
      'fields' => array(
        // Image field.
        'field_bean_image' => array(
          '0' => array(
            'fid' => $files['media-releases']->fid,
            'alt' => t('Media Releases'),
            'title' => t('Media Releases'),
          ),
        ),
        // Text field.
        'field_bean_text' => array(
          '0' => array(
            'value' => 'Vel quis etiam enim pulvinar, tincidunt porttitor dignissim cum, dignissim sociis natoque, elementum nec scelerisque pulvinar, nascetur mauris mauris, a? Rhoncus augue et nunc, adipiscing tincidunt, sagittis, amet!',
            'format' => 'rich_text',
          ),
        ),
        // Link to field.
        'field_link_to' => array(
          '0' => array(
            'url' => $menus['media-releases'],
            'title' => '',
            'attributes' => '',
          ),
        ),
      ),
    ),

    // Events.
    'events' => array(
      'label' => $t('Events'),
      'title' => $t('Events'),
      'description' => $t('Provides a "Events" bean for the News & Media page.'),
      'type' => 'image_and_text',
      'view_mode' => 'default',
      'fields' => array(
        // Image field.
        'field_bean_image' => array(
          '0' => array(
            'fid' => $files['events']->fid,
            'alt' => t('Events'),
            'title' => t('Events'),
          ),
        ),
        // Text field.
        'field_bean_text' => array(
          '0' => array(
            'value' => 'Vel quis etiam enim pulvinar, tincidunt porttitor dignissim cum, dignissim sociis natoque, elementum nec scelerisque pulvinar, nascetur mauris mauris, a? Rhoncus augue et nunc, adipiscing tincidunt, sagittis, amet!',
            'format' => 'rich_text',
          ),
        ),
        // Link to field.
        'field_link_to' => array(
          '0' => array(
            'url' => $menus['events'],
            'title' => '',
            'attributes' => '',
          ),
        ),
      ),
    ),

    // Blog.
    'blog' => array(
      'label' => $t('Blog'),
      'title' => $t('Blog'),
      'description' => $t('Provides a "Blog" bean for the News & Media page.'),
      'type' => 'image_and_text',
      'view_mode' => 'default',
      'fields' => array(
        // Image field.
        'field_bean_image' => array(
          '0' => array(
            'fid' => $files['blog']->fid,
            'alt' => t('Blog'),
            'title' => t('Blog'),
          ),
        ),
        // Text field.
        'field_bean_text' => array(
          '0' => array(
            'value' => 'Vel quis etiam enim pulvinar, tincidunt porttitor dignissim cum, dignissim sociis natoque, elementum nec scelerisque pulvinar, nascetur mauris mauris, a? Rhoncus augue et nunc, adipiscing tincidunt, sagittis, amet!',
            'format' => 'rich_text',
          ),
        ),
        // Link to field.
        'field_link_to' => array(
          '0' => array(
            'url' => $menus['blog'],
            'title' => '',
            'attributes' => '',
          ),
        ),
      ),
    ),
  );

  // Create the beans.
  foreach ($beans as $delta => $bean) {
    BeanFabricator::saveBean($bean['type'], $delta, $bean['label'], $bean['description'], $bean['title'], $bean['fields'], $bean['view_mode']);
  }
}
